[phases.setup]
nixPkgs = [
  "cairo", 
  "pango", 
  "librsvg",
  "gobject-introspection",
  "fontconfig",
  "freetype",
  "glib",
  "harfbuzz",
  "fribidi",
  "pixman"
]

[start]
cmd = "uvicorn app.main:app --host 0.0.0.0 --port $PORT"

[variables]
FONTCONFIG_PATH = "/nix/store/*/etc/fonts:/usr/share/fonts"
WEASYPRINT_DPI = "96"
PANGOCAIRO_BACKEND = "fontconfig" 